name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "058b5c4818dbf5ecf2a07cf88b9e7e4222a0a6f1748f2aa3cfba050ee0514080"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
