name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e617007408561218fa871f4b13131c835a818b5dcd697a2b098ca2e82b343e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
