name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43d525de4d7a4fcc3a4978cbd3d3872967c122ca7f152bcffeabac872775dfd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
